Proyecto_RTDF/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rtdf.urls'))
]

rtdf/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from rtdf.ciencia_datos import *


urlpatterns = [
    path('', views.index, name='index'), 
    path('login/', views.login_view, name="login"),
    path('registro/', views.registro, name='registro'),
    path('pre_registro/', views.pre_registro, name='pre_registro'),
    path('logout/', views.logout_view, name='logout'), 
    path('listado_pacientes/', views.listado_pacientes, name='listado_pacientes'),
    path('vocalizacion/', views.vocalizacion, name='vocalizacion'),
    path('vocalizacion/<int:pauta_id>/', views.vocalizacion, name='vocalizacion_con_pauta'),
    path('intensidad/<int:pauta_id>/', views.intensidad, name='intensidad_con_pauta'),
    path('intensidad/',views.intensidad, name="intensidad"),
    path('list_paci_admin/', views.list_paci_admin, name='list_paci_admin'), 
    path('list_fono_admin/', views.list_fono_admin, name='list_fono_admin'),
    path('list_neur_admin/', views.list_neur_admin, name='list_neur_admin'),
    path('list_fami_admin/', views.list_fami_admin, name='list_fami_admin'),
    path('listado_informes/', views.listado_informes, name='listado_informes'),
    path('detalle_paciente/<int:paciente_id>/', views.detalle_paciente, name='detalle_paciente'),
    path('detalle_fonoaudiologo/<int:fonoaudiologo_id>/', views.detalle_fonoaudiologo, name='detalle_fonoaudiologo'),
    path('detalle_neurologo/<int:neurologo_id>/', views.detalle_neurologo, name='detalle_neurologo'),
    path('detalle_familiar_admin/<int:familiar_id>/', views.detalle_familiar_admin, name='detalle_familiar_admin'),
    path('lista_familiar/', views.lista_familiar, name='lista_familiar'),
    path('detalle_prof_paci/<int:paciente_id>/', views.detalle_prof_paci, name='detalle_prof_paci'),
    path('detalle_familiar/<int:paciente_id>/', views.detalle_familiar, name='detalle_familiar'),
    path('mi_fonoaudiologo/',views.mi_fonoaudiologo,name='mi_fonoaudiologo'),
    path('obtener_provincias/', views.obtener_provincias, name='obtener_provincias'),
    path('obtener_comunas/', views.obtener_comunas, name='obtener_comunas'),
    path('obtener_instituciones/', views.obtener_instituciones, name='obtener_instituciones'),
    path('ingresar_informes/', views.ingresar_informes, name='ingresar_informes'),
    path('editar_informe/<int:informe_id>/', views.editar_informe, name='editar_informe'),
    path('eliminar_informe/<int:informe_id>/', views.eliminar_informe, name='eliminar_informe'),
    path('eliminar_informe_admin/<int:informe_id>/', views.eliminar_informe_admin, name='eliminar_informe_admin'),
    path('detalle_informe/<int:informe_id>/', views.detalle_informe, name='detalle_informe'),
    path('detalle_prof_infor/<int:informe_id>/', views.detalle_prof_infor, name='detalle_prof_infor'),
    path('editar_informe_admin/<int:informe_id>/', views.editar_informe_admin, name='editar_informe_admin'),
    path('pacientes_disponibles/', views.pacientes_disponibles, name='pacientes_disponibles'),
    path('agregar_paciente/<int:paciente_id>/', views.agregar_paciente, name='agregar_paciente'),
    path('desvincular_paciente/<int:paciente_id>/', views.desvincular_paciente, name='desvincular_paciente'),
    path('detalle_prof_pauta/<int:id_pauta_terapeutica_id>/', views.detalle_prof_pauta, name='detalle_prof_pauta'),
    path('editar_prof_pauta/<int:id_pauta_terapeutica_id>/', views.editar_prof_pauta, name='editar_prof_pauta'),
    path('eliminar_prof_pauta/<int:id_pauta_terapeutica_id>/', views.eliminar_prof_pauta, name='eliminar_prof_pauta'),
    
    path('detalle_pauta_admin/<int:id_pauta_terapeutica_id>/', views.detalle_pauta_admin, name='detalle_pauta_admin'),
    path('detalle_pauta_esv_admin/<int:pauta_id>/', views.detalle_pauta_esv_admin, name='detalle_pauta_esv_admin'),

    path('editar_pauta_esv_admin/<int:pauta_id>/', views.editar_pauta_esv_admin, name='editar_pauta_esv_admin'),
    path('eliminar_pauta_esv_admin/<int:pauta_id>/', views.eliminar_pauta_esv_admin, name='eliminar_pauta_esv_admin'),

    path('ciencia_datos/', kmeans_criticidad, name='ciencia_datos'),
    
    path('editar_pauta_admin/<int:id_pauta_terapeutica_id>/', views.editar_pauta_admin, name='editar_pauta_admin'),
    path('eliminar_pauta_admin/<int:id_pauta_terapeutica_id>/', views.eliminar_pauta_admin, name='eliminar_pauta_admin'),
    path('esv/', views.esv, name='esv'),
    path('detalle_esv/<int:informe_id>/', views.detalle_esv, name='detalle_esv'),
    path('editar_esv/<int:informe_id>/', views.editar_esv, name='editar_esv'),
    path('eliminar_informe_esv/<int:informe_id>/', views.eliminar_informe_esv, name='eliminar_informe_esv'),
    path('detalle_esv_admin/<int:informe_id>/', views.detalle_esv_admin, name='detalle_esv_admin'),

    path('eliminar_esv_admin/<int:informe_id>/', views.eliminar_esv_admin, name='eliminar_esv_admin'),
    
    path('analisis_admin/', views.analisis_admin, name='analisis_admin'),
    path('analisis_profe/', views.analisis_profe, name='analisis_profe'),
    path('detalle_audio_admin/<int:audio_id>/', views.detalle_audio_admin, name='detalle_audio_admin'),
    path('detalle_audio_profe/<int:audio_id>/', views.detalle_audio_profe, name='detalle_audio_profe'),
    path('reproducir_audio/<int:audio_id>/', views.reproducir_audio, name='reproducir_audio'),
    path('ingresar_coef_profe/<int:audio_id>/', views.ingresar_coef_profe, name='ingresar_coef_profe'),
    path('eliminar_coef_manual/<int:audiocoeficientes_id>/', views.eliminar_coef_manual, name='eliminar_coef_manual'),
    path('editar_coef_manual/<int:audiocoeficientes_id>/', views.editar_coef_manual, name='editar_coef_manual'),
    path('eliminar_audio_prof/<int:audio_id>/', views.eliminar_audio_prof, name='eliminar_audio_prof'),
    path('eliminar_audio_admin/<int:audio_id>/', views.eliminar_audio_admin, name='eliminar_audio_admin'),
    path('listado_preregistros',views.listado_preregistros, name='listado_preregistros'),
    path('detalle_preregistro/<int:preregistro_id>/', views.detalle_preregistro, name='detalle_preregistro'),
    path('detalle_pauta_esv/<int:pauta_id>/', views.detalle_pauta_esv, name='detalle_pauta_esv'),
    path('escalas_vocales/', views.escalas_vocales, name='escalas_vocales'),
    path('escalas_vocales/<int:pauta_id>/', views.escalas_vocales, name='escalas_vocales_con_pauta'),

    path('editar_pauta_esv/<int:pauta_id>/', views.editar_pauta_esv, name='editar_pauta_esv'),
    path('eliminar_pauta_esv/<int:pauta_id>/', views.eliminar_pauta_esv, name='eliminar_pauta_esv'),

    path('editar_esv_admin/<int:informe_id>/', views.editar_esv_admin, name='editar_esv_admin'),

    #RECUPERAR CONTRASEÑA
    path('recuperar_pw/', views.CustomPasswordResetView.as_view(), name='custom_password_reset'),
    path('recuperar_pw/listo/', views.CustomPasswordResetDoneView.as_view(), name='custom_password_reset_done'),
    path('reiniciar/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='custom_password_reset_confirm'),
    path('reiniciar/listo/', views.CustomPasswordResetCompleteView.as_view(), name='custom_password_reset_complete'),

    path('perfil/<int:usuario_id>/', views.perfil, name='perfil'),
    path('editar_perfil/<int:usuario_id>/', views.editar_perfil, name='editar_perfil'),
    path('analisis_estadistico_profe/<int:informe_id>/', views.analisis_estadistico_profe, name='analisis_estadistico_profe'),
    

]

##urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rtdf/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin, Group, Permission
from django.utils import timezone

####Funcionalidades####

class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('El correo electrónico es obligatorio.')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Los superusuarios deben tener is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Los superusuarios deben tener is_superuser=True.')

        return self.create_user(email, password, **extra_fields)
    
###Tablas del modelamiento creado

class Audio(models.Model):
    id_audio = models.AutoField(primary_key=True)
    url_audio = models.CharField(max_length=200)
    fecha_audio = models.DateTimeField()
    fk_origen_audio = models.ForeignKey('OrigenAudio', on_delete=models.PROTECT, db_column='fk_origen_audio')
    fk_pauta_terapeutica = models.ForeignKey('PautaTerapeutica', on_delete=models.CASCADE, db_column='fk_pauta_terapeutica')

    class Meta:
        db_table = 'audio'
        verbose_name_plural = "audio"

    def __str__(self):
        return self.url_audio    


class Audioscoeficientes(models.Model):
    id_audiocoeficientes = models.AutoField(primary_key=True)
    nombre_archivo = models.CharField(max_length=100)
    fecha_coeficiente = models.DateTimeField()
    f0 = models.CharField(max_length=100)
    f1 = models.CharField(max_length=100)
    f2 = models.CharField(max_length=100)
    f3 = models.CharField(max_length=100)
    f4 = models.CharField(max_length=100)
    intensidad = models.CharField(max_length=100)
    hnr = models.CharField(max_length=100)
    local_jitter = models.CharField(max_length=100)
    local_absolute_jitter = models.CharField(max_length=100)
    rap_jitter = models.CharField(max_length=100)
    ppq5_jitter = models.CharField(max_length=100)
    ddp_jitter = models.CharField(max_length=100)
    local_shimmer = models.CharField(max_length=100)
    local_db_shimmer = models.CharField(max_length=100)
    apq3_shimmer = models.CharField(max_length=100)
    aqpq5_shimmer = models.CharField(max_length=100)
    apq11_shimmer = models.CharField(max_length=100)
    fk_tipo_llenado = models.ForeignKey('TpLlenado', on_delete=models.PROTECT, db_column='fk_tipo_llenado')
    id_audio = models.ForeignKey(Audio, on_delete=models.CASCADE, db_column='id_audio')

    class Meta:
        db_table = 'audioscoeficientes'
        verbose_name_plural = "audiocoeficiente"

    def __str__(self):
        return self.nombre_archivo    

class Comuna(models.Model):
    id_comuna = models.AutoField(primary_key=True)
    comuna = models.CharField(max_length=50)
    id_provincia = models.ForeignKey('Provincia', on_delete=models.CASCADE, db_column='id_provincia')

    class Meta:
        db_table = 'comuna'
        verbose_name_plural = "comuna"

    def __str__(self):
        return self.comuna
    

class EscalaVocales(models.Model):
    id_pauta_terapeutica = models.OneToOneField('PautaTerapeutica', on_delete=models.CASCADE, db_column='id_pauta_terapeutica', primary_key=True)
    palabras = models.TextField()

    class Meta:
        db_table = 'escala_vocales'
        verbose_name_plural = 'escala vocales'

    def __str__(self):
        return self.palabras


class Esv(models.Model):
    id_informe = models.OneToOneField('Informe', on_delete=models.CASCADE, db_column='id_informe', primary_key=True)
    total_esv = models.IntegerField()
    limitacion = models.IntegerField()
    emocional = models.IntegerField()
    fisico = models.IntegerField()

    class Meta:
        db_table = 'esv'
        verbose_name_plural = "esv"
 

class FamiliarPaciente(models.Model):
    id_familiar_paciente = models.AutoField(primary_key=True)
    ##parentesco = models.CharField(max_length=20)
    id_usuario = models.OneToOneField('Usuario', on_delete=models.CASCADE, db_column='id_usuario')
    fk_tipo_familiar = models.ForeignKey('TpFamiliar', on_delete=models.PROTECT, db_column='fk_tipo_familiar',default=1)

    class Meta:
        db_table = 'familiar_paciente'
        verbose_name_plural = "familiar paciente"

    # NO AGREGAR DEBIDO A QUE CONVIERTE EL ID EN STR Y LAS TABLAS VINCULADAS DA ERROR
    # def __str__(self):
    #     return self.id_familiar_paciente    

    def __str__(self):
        return f'{self.fk_tipo_familiar}: {self.id_usuario.primer_nombre} {self.id_usuario.ap_paterno}'

class Grbas(models.Model):
    id_informe = models.OneToOneField('Informe', on_delete=models.CASCADE, db_column='id_informe', primary_key=True)
    g_grado_disfonia = models.CharField(max_length=30)
    r_aspereza = models.CharField(max_length=30)
    b_soplo = models.CharField(max_length=30)
    a_debilidad = models.CharField(max_length=30)
    s_tension = models.CharField(max_length=30)

    class Meta:
        db_table = 'grbas'
        verbose_name_plural = "grbas"

    # def __str__(self):
    #     return self.id_informe    

class Informe(models.Model):
    id_informe = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=200)
    fecha = models.DateTimeField()
    observacion = models.TextField()
    fk_relacion_pa_pro = models.ForeignKey('RelacionPaPro', on_delete=models.PROTECT, db_column='fk_relacion_pa_pro')
    id_audio = models.ForeignKey(Audio, on_delete=models.PROTECT, db_column='id_audio', blank=True, null=True)
    tp_informe = models.ForeignKey('TpInforme', on_delete=models.PROTECT)

    class Meta:
        db_table = 'informe'
        verbose_name_plural = "informe"
    
    def __str__(self):
        return f'Informe: {self.id_informe}' 


class Institucion(models.Model):
    id_institucion = models.AutoField(primary_key=True)
    nombre_institucion = models.CharField(max_length=50)
    id_comuna = models.ForeignKey(Comuna, on_delete=models.CASCADE, db_column='id_comuna')

    class Meta:
        db_table = 'institucion'
        verbose_name_plural = "institucion"        

    def __str__(self):
        return self.nombre_institucion


class Intensidad(models.Model):
    id_pauta_terapeutica = models.OneToOneField('PautaTerapeutica', on_delete=models.CASCADE, db_column='id_pauta_terapeutica', primary_key=True)
    intensidad = models.CharField(max_length=20)
    min_db = models.IntegerField(null=True, blank=True)
    max_db = models.IntegerField(null=True, blank=True)  

    class Meta:
        db_table = 'intensidad'
        verbose_name_plural = "intensidad"



    # def __str__(self):
    #     return self.id_pauta_terapeutica

class OrigenAudio(models.Model):
    id_origen_audio = models.AutoField(primary_key=True)
    origen_audio = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=100)

    class Meta:
        db_table = 'origen_audio'
        verbose_name_plural = "origen audio"

    def __str__(self):
        return self.origen_audio


class Paciente(models.Model):
    id_paciente = models.AutoField(primary_key=True)
    telegram = models.CharField(max_length=30, blank=True, null=True)
    fk_tipo_hipertension = models.ForeignKey('TipoHipertension', on_delete=models.PROTECT, db_column='fk_tipo_hipertension')
    fk_tipo_diabetes = models.ForeignKey('TipoDiabetes', on_delete=models.PROTECT, db_column='fk_tipo_diabetes')
    id_usuario = models.OneToOneField('Usuario', on_delete=models.PROTECT, db_column='id_usuario')

    class Meta:
        db_table = 'paciente'
        verbose_name_plural = "paciente"

    def __str__(self):
        return f'{self.id_usuario.primer_nombre} {self.id_usuario.ap_paterno}'

class Pais(models.Model):
    id_pais = models.AutoField(primary_key=True)
    pais = models.CharField(max_length=60)

    class Meta:
        db_table = 'pais'
        verbose_name_plural = "país"

    def __str__(self):
        return self.pais
    
    
class PalabrasPacientes(models.Model):
    id_palabras_pacientes = models.AutoField(primary_key=True)
    palabras_paciente = models.TextField()

    class Meta:
        db_table = 'palabras_pacientes'
        verbose_name_plural = 'palabras pacientes'

    def __str__(self):
        return self.palabras_paciente


class PautaTerapeutica(models.Model):
    id_pauta_terapeutica = models.AutoField(primary_key=True)
    cant_veces_dia = models.IntegerField()
    descripcion = models.TextField()
    fecha_inicio = models.DateTimeField()
    fecha_fin = models.DateTimeField()
    url_video = models.CharField(max_length=200, blank=True, null=True)
    comentario = models.CharField(max_length=200)
    fk_tp_terapia = models.ForeignKey('TpTerapia',on_delete= models.PROTECT, db_column='fk_tp_terapia')
    # fk_relacion_pa_pro = models.ForeignKey('RelacionPaPro', models.DO_NOTHING, db_column='fk_relacion_pa_pro')
    fk_informe = models.ForeignKey('Informe', on_delete=models.CASCADE, db_column='fk_informe',default=1)

    class Meta:
        db_table = 'pauta_terapeutica'
        verbose_name_plural = "Pauta terapéutica"

    def __str__(self):
        return f'Pauta: {self.id_pauta_terapeutica} | Paciente: {self.fk_informe.fk_relacion_pa_pro.id_paciente.id_usuario.primer_nombre} {self.fk_informe.fk_relacion_pa_pro.id_paciente.id_usuario.ap_paterno}'




class PreRegistro(models.Model):
    id_pre_registro = models.AutoField(primary_key=True)
    numero_identificacion = models.CharField(unique=True, max_length=100)
    primer_nombre = models.CharField(max_length=30)

rtdf/templates/vista_profe/error.html
{% extends 'rtdf/base.html' %}

{% block content %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
    <h1>Error</h1>
    <p>{{ error_message }}</p>
</body>
</html>


{% endblock %}

rtdf/templates/vista_profe/ingresar_coef_profe.html
 {% extends 'rtdf/base.html' %}

    {% block content %}
    
    {% load static %}
    <link rel="stylesheet" href="{% static 'app/css/css_profesionales/editar_coef_manual.css' %}" />
    
    
    
    <body class="is-preload">
        <div class="global-container">
            <div class="card general-form">
                <div class="card-body">
                        
                    <div class="mb-5 mt-3">
                        <a class="btn btn-outline-primary" href="{% url 'detalle_audio_profe' id_audio %}"><i class="fa-solid fa-arrow-left"></i> Volver al análisis del audio N°{{id_audio}} </a>
                    </div>
    
                    <h1 class="card-title text-center">Ingresar Coeficiente Manualmente</h1>
                    <br>
                    <div class="card-text">
    
                        {% if error_message %}
                        <div class="alert alert-danger" role="alert">
                            {{ error_message }}
                        </div>
                        {% endif %}
    
                        <p class="required-message">
                            <span class="asterisk">* </span> Campos requeridos
                        </p>
        {% if coef_manual %}
            <br/>
            <p>Ya hay un registro de coeficiente manual.</p>
        {% else %}
            <form method="post">
                {% csrf_token %}
                <br>
    <!-- Campo: Nombre del audio -->
    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="{{ form.nombre_archivo.id_for_label }}"><i class="fa-solid fa-database"></i>Nombre del audio</label>
            <input type="text" name="{{ form.nombre_archivo.name }}" value="{{ form.nombre_archivo.value }}" readonly>
        </div>
    </div>
    <!-- Campo: Tipo de llenado -->
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="id_fk_tipo_llenado"><i class="fa-solid fa-file-signature"></i>Tipo de llenado</label>
            {{ form.fk_tipo_llenado }}
            <input type="text" style="display: none;" name="{{ form.fk_tipo_llenado.name }}" value="{{ form.fk_tipo_llenado.value }}" readonly>
        </div>
        <div class="form-group col-md-6">
            <label for="{{ form.fecha_coeficiente.id_for_label }}"><i class="fas fa-calendar"></i>Fecha</label></br>
            <input type="datetime-local" class="campo_fecha" id="fecha_coeficiente" name="fecha_coeficiente" value="{% if form.fecha_coeficiente.value|date %}{{ form.fecha_coeficiente.value|date:'Y-m-d\TH:i' }}{% else %}{{ form.fecha_coeficiente.value }}{% endif %}" readonly>
        </div>
    </div>

    <!-- Campo: ID de audio -->
    <div class="form-row">
        <div class="form-group col-md-12">
            <label for="id_id_audio"><i class="fa-solid fa-database"></i>ID de audio</label>
            {{ form.id_audio }}
            <input type="text" style="display: none;" name="{{ form.id_audio.name }}" value="{{ form.id_audio.value }}" readonly>
        </div>
    </div>

    <div class="titulo-tp">
        <h3 class="hh3"> CAMPOS COEFICIENTE</h3>
    </div>
        
    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="f0"><i class="fa-solid fa-file-pen"></i>Coeficiente f0 <span class="required">*</span></label>
            {{ form.f0 }}
            <span class="text-danger">{{ form.f0.errors }}</span>
        </div>

        <div class="form-group col-md-6">
            <label for="f1"><i class="fa-solid fa-file-pen"></i>Coeficiente f1 <span class="required">*</span></label>
            {{ form.f1 }}
            <span class="text-danger">{{ form.f1.errors }}</span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="f2"><i class="fa-solid fa-file-pen"></i>Coeficiente f2 <span class="required">*</span></label>
            {{ form.f2 }}
            <span class="text-danger">{{ form.f2.errors }}</span>
        </div>

        <div class="form-group col-md-6">
            <label for="f3"><i class="fa-solid fa-file-pen"></i>Coeficiente f3 <span class="required">*</span></label>
            {{ form.f3 }}
            <span class="text-danger">{{ form.f3.errors }}</span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="f4"><i class="fa-solid fa-file-pen"></i>Coeficiente f4 <span class="required">*</span></label>
            {{ form.f4 }}
            <span class="text-danger">{{ form.f4.errors }}</span>
        </div>

        <div class="form-group col-md-6">
            <label for="intensidad"><i class="fa-solid fa-file-pen"></i>Intensidad:</label>
            {{ form.intensidad }}
            <span class="text-danger">{{ form.intensidad.errors }}</span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="hnr"><i class="fa-solid fa-file-pen"></i>HNR <span class="required">*</span></label>
            {{ form.hnr }}
            <span class="text-danger">{{ form.hnr.errors }}</span>
        </div>
    

        <div class="form-group col-md-6">
            <label for="local_jitter"><i class="fa-solid fa-file-pen"></i>Local Jitter <span class="required">*</span></label>
            {{ form.local_jitter }}
            <span class="text-danger">{{ form.local_jitter.errors }}</span>
        </div>
    </div>

    <div class="form-row">
        <div class="form-group col-md-6">
            <label for="local_absolute_jitter"><i class="fa-solid fa-file-pen"></i>Local Absolute Jitter <span class="required">*</span></label>
            {{ form.local_absolute_jitter }}
            <span class="text-danger">{{ form.local_absolute_jitter.errors }}</span>
        </div>
   
        <div class="form-group col-md-6">
            <label for="rap_jitter"><i class="fa-solid fa-file-pen"></i>RAP Jitter <span class="required">*</span></label>
            {{ form.rap_jitter }}
            <span class="text-danger">{{ form.rap_jitter.errors }}</span>
        </div>
    </div>

    <div class="form-row">    
        <div class="form-group col-md-6">
            <label for="ppq5_jitter"><i class="fa-solid fa-file-pen"></i>PPQ5 Jitter <span class="required">*</span></label>
            {{ form.ppq5_jitter }}
            <span class="text-danger">{{ form.ppq5_jitter.errors }}</span>
        </div>

        <div class= "form-group col-md-6">
            <label for="ddp_jitter"><i class="fa-solid fa-file-pen"></i>DDP Jitter <span class="required">*</span></label>
            {{ form.ddp_jitter }}
            <span class="text-danger">{{ form.ddp_jitter.errors }}</span>
        </div>
    </div>

    <div class="form-row">    
        <div class="form-group col-md-6">
            <label for="local_shimmer"><i class="fa-solid fa-file-pen"></i>Local Shimmer <span class="required">*</span></label>
            {{ form.local_shimmer }}
            <span class="text-danger">{{ form.local_shimmer.errors }}</span>
        </div>

        <div class="form-group col-md-6">
            <label for="local_db_shimmer"><i class="fa-solid fa-file-pen"></i>Local dB Shimmer <span class="required">*</span></label>
            {{ form.local_db_shimmer }}
            <span class="text-danger">{{ form.local_db_shimmer.errors }}</span>
        </div>
    </div>

    <div class="form-row">  
        <div class="form-group col-md-6">
            <label for="apq3_shimmer"><i class="fa-solid fa-file-pen"></i>APQ3 Shimmer <span class="required">*</span></label>
            {{ form.apq3_shimmer }}
            <span class="text-danger">{{ form.apq3_shimmer.errors }}</span>
        </div>

        <div class="form-group col-md-6">
            <label for="apq5_shimmer"><i class="fa-solid fa-file-pen"></i>APQ5 Shimmer <span class="required">*</span></label>
            {{ form.aqpq5_shimmer }}
            <span class="text-danger">{{ form.aqpq5_shimmer.errors }}</span>
        </div>
    </div>

    <div class="form-row">  
        <div class="form-group col-md-6">
            <label for="apq11_shimmer"><i class="fa-solid fa-file-pen"></i>APQ11 Shimmer <span class="required">*</span></label>
            {{ form.apq11_shimmer }}
            <span class="text-danger">{{ form.apq11_shimmer.errors }}</span>
        </div>
    </div>
    <br/>

                    <button type="submit" class="btn btn-primary mx-auto">Guardar</button>

            </form>

        {% endif %}
    <br/>

    

        </div>
        </div>
        </div>
</body>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script>
        $(document).ready(function () {
            // Selecciona el campo de formulario por su ID
            var selectField = $('#id_fk_tipo_llenado');

            // Desactiva el campo
            selectField.prop('disabled', true);

            // Campo: ID de audio
            var selectIdAudio = $('#id_id_audio');
            selectIdAudio.prop('disabled', true);
        });
    </script>
{% endblock %}